import crypto from 'node:crypto';
import {google} from 'googleapis';
import admin from 'firebase-admin';
import {getDb,json,method,signDownloadToken} from './_lib.js';
const clean=(v,n)=>String(v??'').trim().slice(0,n);
const reviewId=(productId,uid)=>crypto.createHash('sha256').update(`${productId}:${uid}`).digest('hex').slice(0,40);
function drive(){const raw=process.env.GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('Google Drive review storage is not configured.');let sa;try{sa=JSON.parse(raw)}catch{throw new Error('Invalid Google Drive service account.')}const auth=new google.auth.GoogleAuth({credentials:sa,scopes:['https://www.googleapis.com/auth/drive']});return google.drive({version:'v3',auth});}
async function buyer(req){getDb();const t=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();if(!t)throw Object.assign(new Error('A verified buyer account is required.'),{status:401});try{const u=await admin.auth().verifyIdToken(t);if(u.firebase?.sign_in_provider!=='anonymous')throw new Error('Anonymous buyer account required.');return u}catch(e){throw Object.assign(new Error(e.message==='Anonymous buyer account required.'?e.message:'Buyer session expired.'),{status:401});}}
async function paidPurchase(db,productId,uid){const q=await db.collection('orders').where('buyerUid','==',uid).limit(100).get();return q.docs.map(d=>({id:d.id,...d.data()})).find(o=>o.productId===productId&&o.status==='paid')||null;}
async function saveDriveReview(product,review){const folder=clean(product?.sellerReviewsFolderId,200);if(!folder)return;try{const d=drive(),name=`review-${clean(product.id,80)}-${review.id}.json`,q=`'${folder.replace(/'/g,"\\'")}' in parents and name = '${name}' and trashed = false`,found=await d.files.list({q,fields:'files(id)',pageSize:1});const body=JSON.stringify(review);if(found.data.files?.[0]?.id)await d.files.update({fileId:found.data.files[0].id,media:{mimeType:'application/json',body}});else await d.files.create({requestBody:{name,parents:[folder],mimeType:'application/json'},media:{mimeType:'application/json',body}});}catch(e){await getDb().collection('reviewClaims').doc(review.id).set({driveSyncError:String(e.message||'Drive sync failed').slice(0,500)},{merge:true});}}
export default async function handler(req,res){if(!method(req,res,['GET','POST']))return;try{const db=getDb();if(req.method==='GET'){const productId=clean(req.query?.productId,120);if(!productId)return json(res,400,{error:'Product is required.'});const snap=await db.collection('reviewClaims').where('productId','==',productId).where('status','==','complete').limit(500).get();const reviews=snap.docs.map(d=>{const x=d.data()||{};return {id:d.id,rating:Number(x.rating||0),comment:String(x.comment||''),createdAt:x.createdAtISO||'',updatedAt:x.updatedAtISO||'',verifiedBuyer:true,anonymous:true};}).filter(x=>x.rating>=1&&x.rating<=5).sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt)));let eligible=false,myReview=null;if(req.headers.authorization){try{const u=await buyer(req),order=await paidPurchase(db,productId,u.uid);if(order){eligible=true;const id=reviewId(productId,u.uid),r=await db.collection('reviewClaims').doc(id).get();if(r.exists&&r.data()?.status==='complete'){const x=r.data();myReview={id,rating:Number(x.rating),comment:String(x.comment||''),createdAt:x.createdAtISO||'',updatedAt:x.updatedAtISO||''};}}}catch{}}return json(res,200,{reviews,eligible,myReview});}
 const u=await buyer(req),b=req.body&&typeof req.body==='object'?req.body:JSON.parse((await (async()=>{const c=[];for await(const x of req)c.push(Buffer.isBuffer(x)?x:Buffer.from(x));return Buffer.concat(c).toString()}))()||'{}'),productId=clean(b.productId,120),rating=Number(b.rating),comment=clean(b.comment,1200);if(!productId||!Number.isInteger(rating)||rating<1||rating>5||comment.length<3)return json(res,400,{error:'Product, 1–5 rating and a meaningful review are required.'});const productRef=db.collection('products').doc(productId),productSnap=await productRef.get();if(!productSnap.exists)return json(res,404,{error:'Product not found.'});const product=productSnap.data()||{};if(!['published','active'].includes(product.status))return json(res,409,{error:'This product is not currently available for review.'});const orderSnap=await paidPurchase(db,productId,u.uid);if(!orderSnap)return json(res,403,{error:'Only verified buyers can review this product.'});const id=reviewId(productId,u.uid),claimRef=db.collection('reviewClaims').doc(id);let result;await db.runTransaction(async tx=>{const [claim,prod]=await Promise.all([tx.get(claimRef),tx.get(productRef)]);const p=prod.data()||{};if(claim.exists)throw Object.assign(new Error('You have already reviewed this product.'),{status:409});const count=Math.max(0,Number(p.ratingCount||0)),sum=Number.isFinite(Number(p.ratingSum))?Number(p.ratingSum):count*Number(p.ratingAverage||0),nextCount=count+1,nextSum=sum+rating;tx.create(claimRef,{reviewId:id,productId,reviewerUid:u.uid,orderId:orderSnap.id,rating,comment,status:'complete',createdAtISO:new Date().toISOString(),updatedAtISO:new Date().toISOString(),createdAt:admin.firestore.FieldValue.serverTimestamp()});tx.update(productRef,{ratingSum:nextSum,ratingCount:nextCount,ratingAverage:Math.round((nextSum/nextCount)*10)/10,updatedAt:admin.firestore.FieldValue.serverTimestamp()});result={ratingAverage:Math.round((nextSum/nextCount)*10)/10,ratingCount:nextCount};});await saveDriveReview({...product,id:productId},{id,productId,rating,comment,reviewer:'anonymous verified buyer',createdAt:new Date().toISOString()});return json(res,200,{ok:true,...result});}catch(e){json(res,e.status&&e.status<500?e.status:500,{error:e.message||'Unable to save review.'});}}
